package de.greenrobot.daotest;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daotest.LoginTime;

import de.greenrobot.daotest.LoginTimeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginTimeDaoConfig;

    private final LoginTimeDao loginTimeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginTimeDaoConfig = daoConfigMap.get(LoginTimeDao.class).clone();
        loginTimeDaoConfig.initIdentityScope(type);

        loginTimeDao = new LoginTimeDao(loginTimeDaoConfig, this);

        registerDao(LoginTime.class, loginTimeDao);
    }
    
    public void clear() {
        loginTimeDaoConfig.getIdentityScope().clear();
    }

    public LoginTimeDao getLoginTimeDao() {
        return loginTimeDao;
    }

}
