package de.greenrobot.daotest;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOGIN_TIME".
 */
public class LoginTime {

    private Long id;
    /** Not-null value. */
    private String username;
    private java.util.Date date;

    public LoginTime() {
    }

    public LoginTime(Long id) {
        this.id = id;
    }

    public LoginTime(Long id, String username, java.util.Date date) {
        this.id = id;
        this.username = username;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
